name: test and build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Prettier
        run: yarn prettier -c .

      - name: test
        run: yarn test
